### ISSUE TITLE
chrome driver issues

### ISSUE THREAD

**Issue by dominater01** [GateGuy/BatchRomPatcher#1]
even with the right version of chrome and the right version of the chromedriver.exe in the utilities folder the app will not use it and wont popup the firewall thing

and i heard from notnotpat that "with firefox I got what would appear to be program error"

maybe we're doing something wrong idk but the chromedriver.exe wont open can you take alook for us or let us know how to set it up if were doing something wrong, it worked fine with rhdownloader so idk

**Comment by GateGuy** [comment]
Try opening the program directly in command line; if it crashes, copy/paste the error that shows up (and tell notnotpat to do the same). If I had to guess, there might be some import I overlooked that’s on my computer but isn’t built into the executable itself.

**Comment by dominater01** [comment]
theres no error just repeats what it says

1: i just clicked "allow access", try again
2: use firefox driver instead
3: go back

**Comment by NotNotPat** [comment]
That's what I get using firefox 

#####################
# Batch ROM Patcher #
#####################

Traceback (most recent call last):
  File "main.py", line 924, in <module>
  File "main.py", line 65, in main
  File "main.py", line 740, in scrapeWebsite
  File "main.py", line 407, in patchRomsInDir
UnboundLocalError: local variable 'sourceRomName' referenced before assignment
[1368] Failed to execute script main

**Comment by GateGuy** [comment]
@dominater01 There were several problems with Chrome driver that I didn't catch before since I only tested Firefox (I didn't even have Chrome installed on my desktop), but I fixed them and installed/tested Chrome, and it should be working normally now.
@NotNotPat There was a bug involving source roms that aren't pre-zipped, making it crash on a print statement. The only source roms I tested were zipped, so again, I completely overlooked this. It should also be fixed now.

Let me know if you run into any more issues.
